### ISSUE TITLE
I will deploy on Arthera Testnet

### ISSUE THREAD

**Issue by bertux** [Opti-domains/eas-deployment#1]
I have discovered EAS at the workshop presented at EthBarcelona and when I asked if it was possible to deploy on any EVM chain I was replied I can do it on my own.
I want to present a MetIRL demo during EthCC in a few days (Wednesday 19th of July) on Arthera Testnet, and this demo depends on EAS.
So to test your permissionless deployment, I will deploy it on my own and let you know here when it's deployed.
Then I will use this deployment on our own deployment of MetIRL to not depend on another blockchain.

**Comment by bertux** [comment]
When I've tried I got this error:
```
ts-node deploy.ts FACTORY
/home/bert/.config/yarn/global/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS6046: Argument for '--module' option must be: 'none', 'commonjs', 'amd', 'system', 'umd', 'es6', 'es2015', 'es2020', 'esnext'.

    at createTSError (/home/bert/.config/yarn/global/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/bert/.config/yarn/global/node_modules/ts-node/src/index.ts:863:19)
    at createFromPreloadedConfig (/home/bert/.config/yarn/global/node_modules/ts-node/src/index.ts:874:36)
    at phase4 (/home/bert/.config/yarn/global/node_modules/ts-node/src/bin.ts:543:44)
    at bootstrap (/home/bert/.config/yarn/global/node_modules/ts-node/src/bin.ts:95:10)
    at main (/home/bert/.config/yarn/global/node_modules/ts-node/src/bin.ts:55:10)
    at Object.<anonymous> (/home/bert/.config/yarn/global/node_modules/ts-node/src/bin.ts:800:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  diagnosticCodes: [ 6046 ]
}
```

**Comment by Chomtana** [comment]
Sound like typescript or ts-node version incompatibility.

https://github.com/Opti-domains/eas-deployment/blob/a2a5cb87f59385fda681936479d5c80738eed60c/tsconfig.json#L3

Try changing this to esnext.

Anyway, this is the EAS version that is deployed to the Optimism testnet but not the latest one.

**Comment by bertux** [comment]
Thanks, I will retry with the latest one.
